// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJKymE7gWKPUaB2cFLOgxvilbem01C0oU',
    appId: '1:690134956948:web:b5b531f92d68d9afe9ad81',
    messagingSenderId: '690134956948',
    projectId: 'reuse-hub-4b3f7',
    authDomain: 'reuse-hub-4b3f7.firebaseapp.com',
    databaseURL: 'https://reuse-hub-4b3f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reuse-hub-4b3f7.firebasestorage.app',
    measurementId: 'G-47PT7G1K19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDL_jN5ULzH1YQ9dcEPu9dSBLOINs1X68',
    appId: '1:690134956948:android:a3727355e4047d75e9ad81',
    messagingSenderId: '690134956948',
    projectId: 'reuse-hub-4b3f7',
    databaseURL: 'https://reuse-hub-4b3f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reuse-hub-4b3f7.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEmfgvRW6xMZ-NogozSr0Hl9VXZ6j7iTc',
    appId: '1:690134956948:ios:5a905a537395ddb3e9ad81',
    messagingSenderId: '690134956948',
    projectId: 'reuse-hub-4b3f7',
    databaseURL: 'https://reuse-hub-4b3f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reuse-hub-4b3f7.firebasestorage.app',
    iosClientId: '690134956948-g98q2lgrvj8o6ooe01hkc9pej5vtdta0.apps.googleusercontent.com',
    iosBundleId: 'prosen.com.reuseHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJKymE7gWKPUaB2cFLOgxvilbem01C0oU',
    appId: '1:690134956948:web:b5b531f92d68d9afe9ad81',
    messagingSenderId: '690134956948',
    projectId: 'reuse-hub-4b3f7',
    authDomain: 'reuse-hub-4b3f7.firebaseapp.com',
    databaseURL: 'https://reuse-hub-4b3f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reuse-hub-4b3f7.firebasestorage.app',
    measurementId: 'G-47PT7G1K19',
  );
}
